baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "cocoa"

[params]
extracssfiles          = [ "/css/override.css" ]

[[menu.main]]
name                   = "Home"
weight                 = 0
identifier             = "home"
url                    = "/"


[[menu.main]]
name                   = "Deller"
weight                 = 10
identifier             = "deller"
url                    = "/frikadelleopskrifter/"


[[menu.main]]
name                   = "Portfolio"
weight                 = 1
identifier             = "portfolio"
url                    = "/portfolio/"

[[menu.main]]
name                   = "Anmeldelser"
weight                 = 2
identifier             = "anmeldelser"
url                    = "/anmeldelser/"

[[menu.main]]
name                   = "Blog"
weight                 = 3
identifier             = "blog"
url                    = "/blog/"

[[menu.main]]
name                   = "About"
weight                 = 4
identifier             = "about"
url                    = "/about/"

[[menu.main]]
name                   = "Kontakt"
weight                 = 5
identifier             = "contact"
url                    = "/contact/"
